force_multiline_blocks = false
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
max_width = 80
combine_control_expr = false
